command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving_endpoint"
  - name: "DATABRICKS_WAREHOUSE_ID_VALUE"
    valueFrom: "warehouse_id"
  - name: DATABRICKS_TOKEN_VALUE
    valueFrom: "api_token"
  - name: FULL_DATABRICKS_HOST
    valueFrom: "full_databricks_host"
  - name: DATABRICKS_HOST
    valueFrom: "databricks_host"
  - name: CHAT_LOG_TABLE
    valueFrom: "feedback_table"
  - name: LOG_METHOD
    value: dbsql
  # - name: SUPABASE_URL
  # - valueFrom: supabase-url
  # - name: SUPABASE_KEY
  # - valueFrom: supabase-key